FROM node:16-alpine

WORKDIR '/app'

#copy package.json to /client
COPY package.json .
#install all our dependencies
RUN yarn

#copy everything else from our project directory
COPY . .

EXPOSE 8080
EXPOSE 3000

#startup our project
CMD ["yarn", "dev"]