FROM node:14-alpine

WORKDIR '/app'

#copy package.json to /client
COPY ./package.json ./
#install all our dependencies
RUN yarn

#copy everything else from our project directory
COPY . .

COPY chown-chmod.sh /var/www/html/
RUN chmod +x /var/www/html/chown-chmod.sh
RUN rm /var/www/html/chown-chmod.sh

#EXPOSE 8080
#EXPOSE 3000

#startup our project
CMD ["yarn", "dev"]