import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from "next/link";
import React from "react";
// import Posts from '../components/Posts'
// import Pages from '../components/Pages'
// import Items from '../components/Pages'
// import SomePage from './somepage'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {/*<Posts />*/}
        {/*<Pages />*/}
        {/*<Items />*/}
        {/*<SomePage />*/}
          <Link href="/somepage">Somepage</Link>
          <Link href="/test">Test</Link>
      </main>
    </>
  )
}
