version: "3"

services:
  nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    networks:
      - nginxproxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
#      - ./default.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  nginxproxy:
    external:
      name: nginxproxy